security:
  oauth2:
    client:
      clientId: 174474782475-6g83uuip7pc7uk7d246qhqtf75ste5bq.apps.googleusercontent.com
      clientSecret: kDSuL2qp-0t7S5J7bNmbBhqs
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      preEstablishedRedirectUri: http://localhost:8080/user/home
      useCurrentUri: false 
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true